# color_names_rgb
# Define some basic CSS color names and their corresponding RGB values
color_names_rgb = {
    "red": [255, 0, 0],
    "green": [0, 255, 0],
    "blue": [0, 0, 255],
    "yellow": [255, 255, 0],
    "cyan": [0, 255, 255],
    "magenta": [255, 0, 255],
    "white": [255, 255, 255],
    "black": [0, 0, 0],
    "gray": [169, 169, 169],
    "lightgray": [211, 211, 211],
    "darkgray": [169, 169, 169],
    "orange": [255, 165, 0],
    "pink": [255, 192, 203],
    "brown": [139, 69, 19],
    "purple": [128, 0, 128],
    "beige": [245, 245, 220],
    "ivory": [255, 255, 240],
    "lavender": [230, 230, 250],
    "gold": [255, 215, 0],
    "silver": [192, 192, 192],
    "peach": [255, 218, 185],
    "salmon": [250, 128, 114],
    "coral": [255, 127, 80],
    "turquoise": [64, 224, 208],
    "teal": [0, 128, 128],
    "navy": [0, 0, 128],
    "indigo": [75, 0, 130],
    "violet": [238, 130, 238],
    "orchid": [218, 112, 214],
    "plum": [221, 160, 221],
    "wheat": [245, 222, 179],
    "tan": [210, 180, 140],
    "chocolate": [210, 105, 30],
    "crimson": [220, 20, 60],
    "forestgreen": [34, 139, 34],
    "lime": [0, 255, 0],
    "aquamarine": [127, 255, 212],
    "chartreuse": [127, 255, 0],
    "khaki": [240, 230, 140],
    "mintcream": [245, 255, 250],
    "seashell": [255, 245, 238],
    "snow": [255, 250, 250],
    "floralwhite": [255, 250, 240],
    "ghostwhite": [248, 248, 255],
    "blanchedalmond": [255, 235, 205],
    "linen": [250, 240, 230],
    "mistyrose": [255, 228, 225],
    "papayawhip": [255, 239, 179],
    "antiquewhite": [250, 235, 215],
    "bisque": [255, 228, 196],
    "lavenderblush": [255, 240, 245],
    "oldlace": [253, 245, 230],
    "lightgoldenrodyellow": [250, 250, 210],
    "lightpink": [255, 182, 193],
    "mediumvioletred": [199, 21, 133],
}


def _create_color_mapping():
    """Create simplified color name mapping"""

    return {
        "aliceblue": "light blue",
        "antiquewhite": "off-white",
        "aqua": "cyan",
        "aquamarine": "light green",
        "azure": "light blue",
        "beige": "tan",
        "bisque": "orange",
        "black": "black",
        "blanchedalmond": "tan",
        "blue": "blue",
        "blueviolet": "purple",
        "brown": "brown",
        "burlywood": "tan",
        "cadetblue": "blue",
        "chartreuse": "green",
        "chocolate": "brown",
        "coral": "orange",
        "cornflowerblue": "blue",
        "cornsilk": "off-white",
        "crimson": "red",
        "cyan": "cyan",
        "darkblue": "blue",
        "darkcyan": "cyan",
        "darkgoldenrod": "brown",
        "darkgray": "gray",
        "darkgrey": "gray",
        "darkgreen": "green",
        "darkkhaki": "tan",
        "darkmagenta": "purple",
        "darkolivegreen": "green",
        "darkorange": "orange",
        "darkorchid": "purple",
        "darkred": "red",
        "darksalmon": "pink",
        "darkseagreen": "green",
        "darkslateblue": "blue",
        "darkslategray": "gray",
        "darkslategrey": "gray",
        "darkturquoise": "cyan",
        "darkviolet": "purple",
        "deeppink": "pink",
        "deepskyblue": "blue",
        "dimgray": "gray",
        "dimgrey": "gray",
        "dodgerblue": "blue",
        "firebrick": "red",
        "floralwhite": "off-white",
        "forestgreen": "green",
        "fuchsia": "purple",
        "gainsboro": "gray",
        "ghostwhite": "off-white",
        "gold": "yellow",
        "goldenrod": "brown",
        "gray": "gray",
        "grey": "gray",
        "green": "green",
        "greenyellow": "green",
        "honeydew": "off-white",
        "hotpink": "pink",
        "indianred": "red",
        "indigo": "purple",
        "ivory": "off-white",
        "khaki": "tan",
        "lavender": "purple",
        "lavenderblush": "pink",
        "lawngreen": "green",
        "lemonchiffon": "off-white",
        "lightblue": "light blue",
        "lightcoral": "pink",
        "lightcyan": "light blue",
        "lightgoldenrodyellow": "yellow",
        "lightgray": "light gray",
        "lightgrey": "light gray",
        "lightgreen": "light green",
        "lightgoldenrodyellow": "yellow",
        "lightgray": "gray",
        "lightgreen": "green",
        "lightgrey": "gray",
        "lightpink": "pink",
        "lightsalmon": "orange",
        "lightseagreen": "green",
        "lightskyblue": "blue",
        "lightslategray": "gray",
        "lightslategrey": "gray",
        "lightsteelblue": "blue",
        "lightyellow": "yellow",
        "lime": "green",
        "limegreen": "green",
        "linen": "beige",
        "magenta": "pink",
        "maroon": "brown",
        "mediumaquamarine": "green",
        "mediumblue": "blue",
        "mediumorchid": "purple",
        "mediumpurple": "purple",
        "mediumseagreen": "green",
        "mediumslateblue": "blue",
        "mediumspringgreen": "green",
        "mediumturquoise": "blue",
        "mediumvioletred": "red",
        "midnightblue": "blue",
        "mintcream": "white",
        "mistyrose": "pink",
        "moccasin": "yellow",
        "navajowhite": "beige",
        "navy": "blue",
        "oldlace": "beige",
        "olive": "green",
        "olivedrab": "green",
        "orange": "orange",
        "orangered": "red",
        "orchid": "purple",
        "palegoldenrod": "yellow",
        "palegreen": "green",
        "paleturquoise": "blue",
        "palevioletred": "red",
        "papayawhip": "beige",
        "peachpuff": "orange",
        "peru": "brown",
        "pink": "pink",
        "plum": "purple",
        "powderblue": "blue",
        "purple": "purple",
        "red": "red",
        "rosybrown": "brown",
        "royalblue": "blue",
        "saddlebrown": "brown",
        "salmon": "orange",
        "sandybrown": "orange",
        "seagreen": "green",
        "seashell": "beige",
        "sienna": "brown",
        "silver": "gray",
        "skyblue": "blue",
        "slateblue": "blue",
        "slategray": "gray",
        "slategrey": "gray",
        "snow": "white",
        "springgreen": "green",
        "steelblue": "blue",
        "tan": "brown",
        "teal": "green",
        "thistle": "purple",
        "tomato": "red",
        "turquoise": "blue",
        "violet": "purple",
        "wheat": "beige",
        "white": "white",
        "whitesmoke": "gray",
        "yellow": "yellow",
        "yellowgreen": "green",
    }
